name: Package

on:
  push:
  pull_request:

jobs:
  package:
    name: Build & package
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
      - name: Install cc & zip
        run: sudo apt update && sudo apt install -y zip build-essential
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: NPDMTOOL=$DEVKITPRO/tools/bin/npdmtool bash build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xcnx-file-loader
          path: target/skyline-pkg/*.zip
    